### ISSUE TITLE
Use a logging platform

### ISSUE THREAD

**Issue by paked** [BigRoom/vishanti#1]
Maybe something like
- [datadog](https://www.datadoghq.com/)
- [the ELK stack](https://www.elastic.co/products)

**Comment by ZucchiniZe** [comment]
we need to use something that uses a docker agent to record logs, tutum already provides one for datadog, but here is an article that talks about docker logging with logstash http://nathanleclaire.com/blog/2015/04/27/automating-docker-logging-elasticsearch-logstash-kibana-and-logspout/

**Comment by ZucchiniZe** [comment]
also, if we decide to go to the elk route here is a great docker container that has a crap ton of services to assist running the elk stack
- connects with consul, if available
- start sshd
- start logstash
- start diamond
- start StatsD
- start elasticsearch
- start nginx (kibana3)
- start kibana4

https://github.com/ChristianKniep/docker-elk

**Comment by paked** [comment]
Would you like to implement this into our stack @alexb?

**Comment by ZucchiniZe** [comment]
you wronged my name @hcwool

**Comment by paked** [comment]
Geh!

**Comment by paked** [comment]
@ZucchiniZe what do we have to do to close this issue?

**Comment by ZucchiniZe** [comment]
erm, right now I am getting sentry setup but we already have logs, should I create a new issue for it?

**Comment by paked** [comment]
@ZucchiniZe yes.

**Comment by paked** [comment]
Closing because ELK is setup.
