### ISSUE TITLE
Make projects use a nicer logging style

### ISSUE THREAD

**Issue by paked** [BigRoom/vishanti#3]
At the moment I have setup the projects to use the default `log.Print{ln,f}` functions. This leads to all of the logs being structured differently. I would like to move the project over to using another Go logging library in order to help make this consistent and searchable.

Suggestions are:
- [Logrus](https://github.com/Sirupsen/logrus)
- [Log15](https://github.com/inconshreveable/log15)

@ZucchiniZe We can use any logging mechanism as long as it goes to `stdout` right?

---

The current projects which need to be ported are:
- [x] [vision](http://github.com/bigroom/vision)
- [x] [profx](http://github.com/bigroom/profx)
- [x] [zombies](http://github.com/bigroom/zombies)

**Comment by ZucchiniZe** [comment]
correct, and you should start implementing raven (sentry client).
